services:
  mysql:
    image: mysql:8.4
    platform: linux/amd64
    container_name: abora-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: abora
      MYSQL_USER: abora
      MYSQL_PASSWORD: 1306
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: